// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "A versatile tool for backing up and restoring configurations (and, practically, anything)",
  "name": "Jordan Backup",
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 3,
    "revision": 4,
    "text": "0.1.3",
    "timestamp": 1708948684
  },
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "jordan-backup"
    }
  }
};
